server:
  port: 9090
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # 连接数满后的排队数，默认为100
    accept-count: 1000
    threads:
      # tomcat最大线程数，默认为200
      max: 800
      # Tomcat启动初始化的线程数，默认值10
      min-spare: 100
spring:
  application:
    name: ume
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: i18n/messages
  profiles:
    active: dev
  # redis 配置
  redis:
    # 地址
#    host: 47.94.206.225
    host: 127.0.0.1
    #host: 192.168.1.105
    # 端口，默认为6379
    port: 6379
    # 数据库索引
    database: 0
    # 密码
    password: 123456
    #    password:
    # 连接超时时间
    timeout: 500
    jedis:
      pool:
        max-active: 50
        max-wait: 5000
        max-idle: 70
        min-idle: 0
  #    lettuce:
  #      pool:
  #        # 连接池中的最小空闲连接
  #        min-idle: 0
  #        # 连接池中的最大空闲连接
  #        max-idle: 8
  #        # 连接池的最大数据库连接数
  #        max-active: 8
  #        # #连接池最大阻塞等待时间（使用负值表示没有限制）
  #        max-wait: -1ms
  #swagger3配置
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
#rabbitMQ配置
#消息队列
  rabbitmq:
#    host: 127.0.0.1
    host: 127.0.0.1
    port: 5672
    #虚拟host 可以不设置,使用server默认host
    #virtual-host: /env-dev
    password: guest
    username: guest
    #前端js连接端口
#    stompport: 61613
#    #开启手动确认消息
#    listener:
#      simple:
#        #  采用手动应答
#        acknowledge-mode: manual
#    #开启confirmCallback 生产者到broker的交换机——消息二次确认
#    publisher-confirm-type: correlated
#    #开启returnCallback配置 交换机到队列的可靠性投递——消息二次确认
#    publisher-returns: true
#    #修改交换机投递到队列失败的策略  true:交换机处理消息到路由失败，返回给生产者
#    template:
#      mandatory: true
  main:
    allow-bean-definition-overriding: true
  # 请求前缀
  #pathMapping: /dev-api
# MyBatisPlus配置
# https://baomidou.com/config/
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDeleted # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)